### PR TITLE
Fix pelican-toc to work with pelican 4.5.0

### PR DESCRIPTION
**Pull request by manuelakuhn**
Since python2 support was removed in pelican 4.5.0 pelican-toc does not work any more and thus the IPSY Docs as well.
The error message is:
```
ERROR: Cannot load plugin `pelican-toc`
  | cannot import name 'python_2_unicode_compatible' from 'pelican.utils' (~/.venvs/pelican/lib64/python3.8/site-packages/pelican/utils.py)
CRITICAL: Error encountered
```
A quick and easy fix is to load python_2_unicode_compatible inside pelican-toc from the six module instead.

### CODE REVIEW

**Comment by aqw** [comment]
Merged. Thanks!
